resolver: lts-13.26
compiler: ghc-8.6.5
packages:
  - contra-tracer
  - iohk-monitoring
  - tracer-transformers

extra-deps:
  - time-units-1.0.0
  - prometheus-2.1.2
    #  - git: https://github.com/CodiePP/ekg-prometheus-adapter
    #    commit: 1a258b6df7d9807d4c4ff3e99722223d31a2c320

nix:
  shell-file: scripts/nix/stack-shell.nix
