# from https://www.stackage.org/lts

resolver: lts-21.9
compiler: ghc-9.4.6

#resolver: lts-20.25
#compiler: ghc-9.2.8

#resolver: lts-19.19
#compiler: ghc-8.10.7

#resolver: lts-14.27
#compiler: ghc-8.6.5

#resolver: nightly-2020-08-26
#compiler: ghc-8.10.2

packages:
  - contra-tracer
  - tracer-transformers
  - hs-monitoring
  - plugins/backend-aggregation
  - plugins/backend-graylog
  - plugins/backend-monitoring
  - plugins/backend-trace-acceptor
  - plugins/backend-trace-forwarder
  - plugins/scribe-systemd
  - examples

allow-newer: true

extra-deps:
  - async-timer-0.2.0.0
  - network-3.1.1.1

  - time-units-1.0.0
  - katip-0.8.7.4

  - git: https://github.com/input-output-hk/ouroboros-network
    commit: a09f209bb6bbb1a1a9a5b31d671da0189001e175
    subdirs:
        - Win32-network

  - git: https://github.com/CodiePP/libsystemd-journal
    commit: c5a495f0ee41fd2aea8c4d7db322b594f5b042a2
    # commit: 49ad111e668e0d6e06e759a13d8de311bc91e149
    subdirs:
        - .

nix:
  pure: false
#  shell-file: stack.nix
  packages: [ zlib.dev, zlib.out
            , openssl.dev, openssl.out
            , libsodium.dev, libsodium.out
            , haskell.compiler.ghc94
            , pkg-config
            , systemd.dev
            ]
