resolver: lts-13.26
compiler: ghc-8.6.5
packages:
  - contra-tracer
  - tracer-transformers
  - iohk-monitoring
  - plugins/backend-aggregation
  - plugins/backend-editor
  - plugins/backend-ekg
  - plugins/backend-graylog
  - plugins/backend-monitoring
  - plugins/scribe-systemd
  - examples

extra-deps:
  - time-units-1.0.0
  - prometheus-2.1.2
  - libsystemd-journal-1.4.4
  - katip-0.8.3.0
  - git: https://github.com/CodiePP/ekg-prometheus-adapter
    commit: 1a258b6df7d9807d4c4ff3e99722223d31a2c320

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 3c40edcf5bdba8721d3430d0aaaeea8770ce9bec
    subdirs:
      - .
      - test

  - git: http://github.com/well-typed/canonical-json
    commit: ddfe3593b80b5ceb88842bb7a6f2268df75d2c2f

nix:
  shell-file: scripts/nix/stack-shell.nix
